# frozen_string_literal: true

# Solid Cache entries table. The schema is loaded from
# db/cache_schema.rb (auto-generated by `rails g solid_cache:install`)
# so we keep that in sync rather than re-typing it here.
class CreateSolidCacheEntries < ActiveRecord::Migration[8.1]
  def change
    # Defer to the Solid Cache canonical schema.
    require Rails.root.join('db/cache_schema.rb')
  end
end
